// <auto-generated />
namespace Hever.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190819_Amit_Annotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190819_Amit_Annotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201908071414298_20190819_Amit_Annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
