// <auto-generated />
namespace Hever.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Einor2405 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Einor2405));
        
        string IMigrationMetadata.Id
        {
            get { return "201905240843436_Einor2405"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
